[package]
name = "lxmf"
version = "0.1.0"
edition = "2021"

[dependencies]
reticulum = { path = "../Reticulum-rs" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
rmp-serde = "1"
serde_json = "1"
