[package]
name = "lxmf"
version = "0.1.0"
edition = "2021"

[dependencies]
reticulum = { path = "../Reticulum-rs" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
rmp-serde = "1"
serde_json = "1"
sha2 = "0.10"
hkdf = "0.12"
tempfile = "3"
hex = "0.4"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
clap = { version = "4.5.4", features = ["derive"] }
